// Generated by gencpp from file neo_srvs/ActivateMotors.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_ACTIVATEMOTORS_H
#define NEO_SRVS_MESSAGE_ACTIVATEMOTORS_H

#include <ros/service_traits.h>


#include <neo_srvs/ActivateMotorsRequest.h>
#include <neo_srvs/ActivateMotorsResponse.h>


namespace neo_srvs
{

struct ActivateMotors
{

typedef ActivateMotorsRequest Request;
typedef ActivateMotorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActivateMotors
} // namespace neo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_srvs::ActivateMotors > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::neo_srvs::ActivateMotors&) { return value(); }
};

template<>
struct DataType< ::neo_srvs::ActivateMotors > {
  static const char* value()
  {
    return "neo_srvs/ActivateMotors";
  }

  static const char* value(const ::neo_srvs::ActivateMotors&) { return value(); }
};


// service_traits::MD5Sum< ::neo_srvs::ActivateMotorsRequest> should match
// service_traits::MD5Sum< ::neo_srvs::ActivateMotors >
template<>
struct MD5Sum< ::neo_srvs::ActivateMotorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::ActivateMotors >::value();
  }
  static const char* value(const ::neo_srvs::ActivateMotorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::ActivateMotorsRequest> should match
// service_traits::DataType< ::neo_srvs::ActivateMotors >
template<>
struct DataType< ::neo_srvs::ActivateMotorsRequest>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::ActivateMotors >::value();
  }
  static const char* value(const ::neo_srvs::ActivateMotorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_srvs::ActivateMotorsResponse> should match
// service_traits::MD5Sum< ::neo_srvs::ActivateMotors >
template<>
struct MD5Sum< ::neo_srvs::ActivateMotorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::ActivateMotors >::value();
  }
  static const char* value(const ::neo_srvs::ActivateMotorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::ActivateMotorsResponse> should match
// service_traits::DataType< ::neo_srvs::ActivateMotors >
template<>
struct DataType< ::neo_srvs::ActivateMotorsResponse>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::ActivateMotors >::value();
  }
  static const char* value(const ::neo_srvs::ActivateMotorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_SRVS_MESSAGE_ACTIVATEMOTORS_H
