// Generated by gencpp from file neo_srvs/IOBoardSetDigOut.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_IOBOARDSETDIGOUT_H
#define NEO_SRVS_MESSAGE_IOBOARDSETDIGOUT_H

#include <ros/service_traits.h>


#include <neo_srvs/IOBoardSetDigOutRequest.h>
#include <neo_srvs/IOBoardSetDigOutResponse.h>


namespace neo_srvs
{

struct IOBoardSetDigOut
{

typedef IOBoardSetDigOutRequest Request;
typedef IOBoardSetDigOutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IOBoardSetDigOut
} // namespace neo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_srvs::IOBoardSetDigOut > {
  static const char* value()
  {
    return "2f1355cc54f74167e7674386afa4efe9";
  }

  static const char* value(const ::neo_srvs::IOBoardSetDigOut&) { return value(); }
};

template<>
struct DataType< ::neo_srvs::IOBoardSetDigOut > {
  static const char* value()
  {
    return "neo_srvs/IOBoardSetDigOut";
  }

  static const char* value(const ::neo_srvs::IOBoardSetDigOut&) { return value(); }
};


// service_traits::MD5Sum< ::neo_srvs::IOBoardSetDigOutRequest> should match
// service_traits::MD5Sum< ::neo_srvs::IOBoardSetDigOut >
template<>
struct MD5Sum< ::neo_srvs::IOBoardSetDigOutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::IOBoardSetDigOut >::value();
  }
  static const char* value(const ::neo_srvs::IOBoardSetDigOutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::IOBoardSetDigOutRequest> should match
// service_traits::DataType< ::neo_srvs::IOBoardSetDigOut >
template<>
struct DataType< ::neo_srvs::IOBoardSetDigOutRequest>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::IOBoardSetDigOut >::value();
  }
  static const char* value(const ::neo_srvs::IOBoardSetDigOutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_srvs::IOBoardSetDigOutResponse> should match
// service_traits::MD5Sum< ::neo_srvs::IOBoardSetDigOut >
template<>
struct MD5Sum< ::neo_srvs::IOBoardSetDigOutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::IOBoardSetDigOut >::value();
  }
  static const char* value(const ::neo_srvs::IOBoardSetDigOutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::IOBoardSetDigOutResponse> should match
// service_traits::DataType< ::neo_srvs::IOBoardSetDigOut >
template<>
struct DataType< ::neo_srvs::IOBoardSetDigOutResponse>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::IOBoardSetDigOut >::value();
  }
  static const char* value(const ::neo_srvs::IOBoardSetDigOutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_SRVS_MESSAGE_IOBOARDSETDIGOUT_H
