// Generated by gencpp from file neo_srvs/RelayBoardSetRelay.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_RELAYBOARDSETRELAY_H
#define NEO_SRVS_MESSAGE_RELAYBOARDSETRELAY_H

#include <ros/service_traits.h>


#include <neo_srvs/RelayBoardSetRelayRequest.h>
#include <neo_srvs/RelayBoardSetRelayResponse.h>


namespace neo_srvs
{

struct RelayBoardSetRelay
{

typedef RelayBoardSetRelayRequest Request;
typedef RelayBoardSetRelayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelayBoardSetRelay
} // namespace neo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetRelay > {
  static const char* value()
  {
    return "2f1355cc54f74167e7674386afa4efe9";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetRelay&) { return value(); }
};

template<>
struct DataType< ::neo_srvs::RelayBoardSetRelay > {
  static const char* value()
  {
    return "neo_srvs/RelayBoardSetRelay";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetRelay&) { return value(); }
};


// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetRelayRequest> should match
// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetRelay >
template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetRelayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::RelayBoardSetRelay >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetRelayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::RelayBoardSetRelayRequest> should match
// service_traits::DataType< ::neo_srvs::RelayBoardSetRelay >
template<>
struct DataType< ::neo_srvs::RelayBoardSetRelayRequest>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::RelayBoardSetRelay >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetRelayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetRelayResponse> should match
// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetRelay >
template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetRelayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::RelayBoardSetRelay >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetRelayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::RelayBoardSetRelayResponse> should match
// service_traits::DataType< ::neo_srvs::RelayBoardSetRelay >
template<>
struct DataType< ::neo_srvs::RelayBoardSetRelayResponse>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::RelayBoardSetRelay >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetRelayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_SRVS_MESSAGE_RELAYBOARDSETRELAY_H
