// Generated by gencpp from file neo_srvs/RelayBoardSetLCDMsg.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_RELAYBOARDSETLCDMSG_H
#define NEO_SRVS_MESSAGE_RELAYBOARDSETLCDMSG_H

#include <ros/service_traits.h>


#include <neo_srvs/RelayBoardSetLCDMsgRequest.h>
#include <neo_srvs/RelayBoardSetLCDMsgResponse.h>


namespace neo_srvs
{

struct RelayBoardSetLCDMsg
{

typedef RelayBoardSetLCDMsgRequest Request;
typedef RelayBoardSetLCDMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelayBoardSetLCDMsg
} // namespace neo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetLCDMsg > {
  static const char* value()
  {
    return "8b7095eb8dcd517ba7c37a0a06dcc50b";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsg&) { return value(); }
};

template<>
struct DataType< ::neo_srvs::RelayBoardSetLCDMsg > {
  static const char* value()
  {
    return "neo_srvs/RelayBoardSetLCDMsg";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsg&) { return value(); }
};


// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetLCDMsgRequest> should match
// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetLCDMsg >
template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetLCDMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::RelayBoardSetLCDMsg >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::RelayBoardSetLCDMsgRequest> should match
// service_traits::DataType< ::neo_srvs::RelayBoardSetLCDMsg >
template<>
struct DataType< ::neo_srvs::RelayBoardSetLCDMsgRequest>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::RelayBoardSetLCDMsg >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetLCDMsgResponse> should match
// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetLCDMsg >
template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetLCDMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::RelayBoardSetLCDMsg >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::RelayBoardSetLCDMsgResponse> should match
// service_traits::DataType< ::neo_srvs::RelayBoardSetLCDMsg >
template<>
struct DataType< ::neo_srvs::RelayBoardSetLCDMsgResponse>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::RelayBoardSetLCDMsg >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_SRVS_MESSAGE_RELAYBOARDSETLCDMSG_H
