// Generated by gencpp from file neo_srvs/RelayBoardSetLCDMsgRequest.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_RELAYBOARDSETLCDMSGREQUEST_H
#define NEO_SRVS_MESSAGE_RELAYBOARDSETLCDMSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_srvs
{
template <class ContainerAllocator>
struct RelayBoardSetLCDMsgRequest_
{
  typedef RelayBoardSetLCDMsgRequest_<ContainerAllocator> Type;

  RelayBoardSetLCDMsgRequest_()
    : message()  {
    }
  RelayBoardSetLCDMsgRequest_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelayBoardSetLCDMsgRequest_

typedef ::neo_srvs::RelayBoardSetLCDMsgRequest_<std::allocator<void> > RelayBoardSetLCDMsgRequest;

typedef boost::shared_ptr< ::neo_srvs::RelayBoardSetLCDMsgRequest > RelayBoardSetLCDMsgRequestPtr;
typedef boost::shared_ptr< ::neo_srvs::RelayBoardSetLCDMsgRequest const> RelayBoardSetLCDMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator1> & lhs, const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator1> & lhs, const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace neo_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_srvs/RelayBoardSetLCDMsgRequest";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
;
  }

  static const char* value(const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelayBoardSetLCDMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_srvs::RelayBoardSetLCDMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_SRVS_MESSAGE_RELAYBOARDSETLCDMSGREQUEST_H
