// Generated by gencpp from file neo_srvs/RelayBoardSetEMStop.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_RELAYBOARDSETEMSTOP_H
#define NEO_SRVS_MESSAGE_RELAYBOARDSETEMSTOP_H

#include <ros/service_traits.h>


#include <neo_srvs/RelayBoardSetEMStopRequest.h>
#include <neo_srvs/RelayBoardSetEMStopResponse.h>


namespace neo_srvs
{

struct RelayBoardSetEMStop
{

typedef RelayBoardSetEMStopRequest Request;
typedef RelayBoardSetEMStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelayBoardSetEMStop
} // namespace neo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetEMStop > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetEMStop&) { return value(); }
};

template<>
struct DataType< ::neo_srvs::RelayBoardSetEMStop > {
  static const char* value()
  {
    return "neo_srvs/RelayBoardSetEMStop";
  }

  static const char* value(const ::neo_srvs::RelayBoardSetEMStop&) { return value(); }
};


// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetEMStopRequest> should match
// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetEMStop >
template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetEMStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::RelayBoardSetEMStop >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetEMStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::RelayBoardSetEMStopRequest> should match
// service_traits::DataType< ::neo_srvs::RelayBoardSetEMStop >
template<>
struct DataType< ::neo_srvs::RelayBoardSetEMStopRequest>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::RelayBoardSetEMStop >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetEMStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetEMStopResponse> should match
// service_traits::MD5Sum< ::neo_srvs::RelayBoardSetEMStop >
template<>
struct MD5Sum< ::neo_srvs::RelayBoardSetEMStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::RelayBoardSetEMStop >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetEMStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::RelayBoardSetEMStopResponse> should match
// service_traits::DataType< ::neo_srvs::RelayBoardSetEMStop >
template<>
struct DataType< ::neo_srvs::RelayBoardSetEMStopResponse>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::RelayBoardSetEMStop >::value();
  }
  static const char* value(const ::neo_srvs::RelayBoardSetEMStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_SRVS_MESSAGE_RELAYBOARDSETEMSTOP_H
