// Generated by gencpp from file neo_srvs/ResetOmniWheels.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_RESETOMNIWHEELS_H
#define NEO_SRVS_MESSAGE_RESETOMNIWHEELS_H

#include <ros/service_traits.h>


#include <neo_srvs/ResetOmniWheelsRequest.h>
#include <neo_srvs/ResetOmniWheelsResponse.h>


namespace neo_srvs
{

struct ResetOmniWheels
{

typedef ResetOmniWheelsRequest Request;
typedef ResetOmniWheelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetOmniWheels
} // namespace neo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_srvs::ResetOmniWheels > {
  static const char* value()
  {
    return "fc4174458451e931b5704dcb756e00b4";
  }

  static const char* value(const ::neo_srvs::ResetOmniWheels&) { return value(); }
};

template<>
struct DataType< ::neo_srvs::ResetOmniWheels > {
  static const char* value()
  {
    return "neo_srvs/ResetOmniWheels";
  }

  static const char* value(const ::neo_srvs::ResetOmniWheels&) { return value(); }
};


// service_traits::MD5Sum< ::neo_srvs::ResetOmniWheelsRequest> should match
// service_traits::MD5Sum< ::neo_srvs::ResetOmniWheels >
template<>
struct MD5Sum< ::neo_srvs::ResetOmniWheelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::ResetOmniWheels >::value();
  }
  static const char* value(const ::neo_srvs::ResetOmniWheelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::ResetOmniWheelsRequest> should match
// service_traits::DataType< ::neo_srvs::ResetOmniWheels >
template<>
struct DataType< ::neo_srvs::ResetOmniWheelsRequest>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::ResetOmniWheels >::value();
  }
  static const char* value(const ::neo_srvs::ResetOmniWheelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_srvs::ResetOmniWheelsResponse> should match
// service_traits::MD5Sum< ::neo_srvs::ResetOmniWheels >
template<>
struct MD5Sum< ::neo_srvs::ResetOmniWheelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::ResetOmniWheels >::value();
  }
  static const char* value(const ::neo_srvs::ResetOmniWheelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::ResetOmniWheelsResponse> should match
// service_traits::DataType< ::neo_srvs::ResetOmniWheels >
template<>
struct DataType< ::neo_srvs::ResetOmniWheelsResponse>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::ResetOmniWheels >::value();
  }
  static const char* value(const ::neo_srvs::ResetOmniWheelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_SRVS_MESSAGE_RESETOMNIWHEELS_H
