// Generated by gencpp from file neo_srvs/UnlockPlatform.msg
// DO NOT EDIT!


#ifndef NEO_SRVS_MESSAGE_UNLOCKPLATFORM_H
#define NEO_SRVS_MESSAGE_UNLOCKPLATFORM_H

#include <ros/service_traits.h>


#include <neo_srvs/UnlockPlatformRequest.h>
#include <neo_srvs/UnlockPlatformResponse.h>


namespace neo_srvs
{

struct UnlockPlatform
{

typedef UnlockPlatformRequest Request;
typedef UnlockPlatformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UnlockPlatform
} // namespace neo_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_srvs::UnlockPlatform > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::neo_srvs::UnlockPlatform&) { return value(); }
};

template<>
struct DataType< ::neo_srvs::UnlockPlatform > {
  static const char* value()
  {
    return "neo_srvs/UnlockPlatform";
  }

  static const char* value(const ::neo_srvs::UnlockPlatform&) { return value(); }
};


// service_traits::MD5Sum< ::neo_srvs::UnlockPlatformRequest> should match
// service_traits::MD5Sum< ::neo_srvs::UnlockPlatform >
template<>
struct MD5Sum< ::neo_srvs::UnlockPlatformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::UnlockPlatform >::value();
  }
  static const char* value(const ::neo_srvs::UnlockPlatformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::UnlockPlatformRequest> should match
// service_traits::DataType< ::neo_srvs::UnlockPlatform >
template<>
struct DataType< ::neo_srvs::UnlockPlatformRequest>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::UnlockPlatform >::value();
  }
  static const char* value(const ::neo_srvs::UnlockPlatformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_srvs::UnlockPlatformResponse> should match
// service_traits::MD5Sum< ::neo_srvs::UnlockPlatform >
template<>
struct MD5Sum< ::neo_srvs::UnlockPlatformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_srvs::UnlockPlatform >::value();
  }
  static const char* value(const ::neo_srvs::UnlockPlatformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_srvs::UnlockPlatformResponse> should match
// service_traits::DataType< ::neo_srvs::UnlockPlatform >
template<>
struct DataType< ::neo_srvs::UnlockPlatformResponse>
{
  static const char* value()
  {
    return DataType< ::neo_srvs::UnlockPlatform >::value();
  }
  static const char* value(const ::neo_srvs::UnlockPlatformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_SRVS_MESSAGE_UNLOCKPLATFORM_H
