// Generated by gencpp from file neo_msgs/Keypad.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_KEYPAD_H
#define NEO_MSGS_MESSAGE_KEYPAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neo_msgs
{
template <class ContainerAllocator>
struct Keypad_
{
  typedef Keypad_<ContainerAllocator> Type;

  Keypad_()
    : header()
    , button()  {
      button.assign(false);
  }
  Keypad_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , button()  {
  (void)_alloc;
      button.assign(false);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint8_t, 5>  _button_type;
  _button_type button;





  typedef boost::shared_ptr< ::neo_msgs::Keypad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::Keypad_<ContainerAllocator> const> ConstPtr;

}; // struct Keypad_

typedef ::neo_msgs::Keypad_<std::allocator<void> > Keypad;

typedef boost::shared_ptr< ::neo_msgs::Keypad > KeypadPtr;
typedef boost::shared_ptr< ::neo_msgs::Keypad const> KeypadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::Keypad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::Keypad_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::neo_msgs::Keypad_<ContainerAllocator1> & lhs, const ::neo_msgs::Keypad_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.button == rhs.button;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::neo_msgs::Keypad_<ContainerAllocator1> & lhs, const ::neo_msgs::Keypad_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace neo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::Keypad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::Keypad_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::Keypad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::Keypad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::Keypad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::Keypad_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::Keypad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21d087e667f5f91b3508131e477c1aa8";
  }

  static const char* value(const ::neo_msgs::Keypad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21d087e667f5f91bULL;
  static const uint64_t static_value2 = 0x3508131e477c1aa8ULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::Keypad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/Keypad";
  }

  static const char* value(const ::neo_msgs::Keypad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::Keypad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"std_msgs/Header header\n"
"\n"
"bool[5] button #5 button keypad\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::neo_msgs::Keypad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::Keypad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Keypad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::Keypad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::Keypad_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "button[]" << std::endl;
    for (size_t i = 0; i < v.button.size(); ++i)
    {
      s << indent << "  button[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.button[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_KEYPAD_H
